name: Install Qt
  # You may pin to the exact commit or the version.
  # uses: jurplel/install-qt-action@a962fb91949c8e846a3e4a944d50e7ef5cc3a28a
  uses: jurplel/install-qt-action@v2.11.1
  with:
    # Directory to install Qt
    dir: # optional
    # Version of Qt to install
    version: # optional, default is 5.15.2
    # Host platform
    host: # optional
    # Target platform for build
    target: # optional, default is desktop
    # Architecture for Windows/Android
    arch: # optional
    # Whether or not to install Qt dependencies on Linux
    install-deps: # optional, default is true
    # Additional Qt modules to install
    modules: # optional
    # Force a Qt mirror in case the default is not working
    mirror: # optional
    # Whether or not to actually download Qt
    cached: # optional, default is false
    # Whether or not to automatically run setup-python to find a valid python version.
    setup-python: # optional, default is true
    # Qt tools to download--specify comma-separated argument lists which are themselves separated by spaces: <tool_name>,<tool_version>,<tool_arch>
    tools: # optional
    # Whether or not to actually install Qt or just the tools from the tools argument
    tools-only: # optional, default is false
    # Version of aqtinstall to use in case of issues
    aqtversion: # optional, default is ==0.10.0
    # Version of py7zr to use in case of issues
    py7zrversion: # optional, default is ==0.11.0
    # Any extra arguments to append to the back
    extra: # optional
